source 'https://rubygems.org'

gem "rake"
gem "path"
gem "json", "2.2.0"
gem 'codecov', :require => false, :group => :test
gem 'minitest' group: :test
gem 'simplecov', require: false, group: :test
gem 'simplecov-cobertura'
gem 'solargraph', group: :development

gem 'discordrb'
